using System;
using System.Collections.Generic;
using radians.beamlab;
using static radians.beamlab.GeoMath;

namespace radians.beamlab.app;

/// <summary>
/// WP6: space-station e.i.r.p. mask generation per Rec. S.1503-4 Sec. C3.2 --
/// "the maximum e.i.r.p. generated by a non-GSO space station as a function
/// of the angle seen from the space station between the line to its sub-point
/// and a point on the GSO arc", with G(theta) "corresponding to the
/// aggregation of all beams". For each latitude block the scene is rebuilt
/// there and the composite EIRP is enveloped over azimuth at each angle --
/// and over the reachable pass headings (the WP4 configuration set), since
/// the GSO-arc direction is Earth-referenced while the layout flies with the
/// orbit. No yaw sweep is needed here, unlike the pfd samplers: body yaw is
/// a rigid rotation of the composite about nadir, and the per-angle azimuth
/// envelope is invariant under it.
/// </summary>
public static class SatEirpMaskBuilder
{
    public static EirpMaskTable Build(PfdMaskViewModel live, double inclinationDeg,
        IReadOnlyList<double> latitudesDeg, IReadOnlyList<double> anglesDeg,
        int azimuthSamples = 180)
    {
        var gen = new PfdMaskViewModel(live.Coastlines);
        live.CopySettingsTo(gen);

        var table = new EirpMaskTable();
        foreach (double lat in latitudesDeg)
        {
            var headings = new List<double>(2);
            if (GroundTrack.HeadingsAtLatitude(inclinationDeg, lat) is { } h)
            {
                headings.Add(h.AscendingDeg);
                double sep = Math.Abs((((h.DescendingDeg - h.AscendingDeg) % 360.0) + 360.0) % 360.0);
                if (sep > 1e-9 && Math.Abs(sep - 360.0) > 1e-9) headings.Add(h.DescendingDeg);
            }
            else
            {
                headings.Add(90.0);
            }

            var block = new EirpLatBlock { LatDeg = lat };
            var env = new double[anglesDeg.Count];
            for (int i = 0; i < env.Length; i++) env[i] = double.NegativeInfinity;

            foreach (double psi in headings)
            {
                gen.Scene.SubSatLatDeg = lat;
                gen.Scene.BodyYawDeg = psi;
                gen.RebuildForCompute();
                var beams = gen.Scene.Beams;
                var powers = PfdMaskField.BeamPowersDbw(gen);
                var (north, east, down) = SatNedBasis(gen.Scene.SubSatLatDeg, gen.Scene.SubSatLonDeg);

                for (int i = 0; i < anglesDeg.Count; i++)
                {
                    // Envelope over azimuth: the GSO-arc point can sit at any
                    // bearing, so the mask at angle theta is the worst case.
                    double best = double.NegativeInfinity;
                    for (int k = 0; k < azimuthSamples; k++)
                    {
                        double az = 360.0 * k / azimuthSamples;
                        var dir = NedToEcef(BeamDirNed(anglesDeg[i], az), north, east, down).Normalized();
                        double e = BeamComposer.CompositeEirpDbw(beams, dir, powers);
                        if (e > best) best = e;
                    }
                    if (best > env[i]) env[i] = best;
                }
            }

            for (int i = 0; i < anglesDeg.Count; i++)
                block.ByAngle.Add((anglesDeg[i], env[i]));
            table.Blocks.Add(block);
        }
        return table;
    }
}
